import * as itineraryService from './itineraryService.js';
import * as userService from './userService.js';

/**
 * GenerationService — High-level orchestrator for date generation.
 * Handles usage checks, AI generation, and persistence.
 */

export const generatePlanFlow = async (supabase, userId, params, type = 'classic') => {
    // 1. Check Usage Limits
    const usage = await userService.checkUsageLimits(supabase, userId, type);
    if (!usage.allowed) {
        throw { status: 403, message: 'Limit reached', code: 'LIMIT_REACHED' };
    }

    // 2. Generate Itinerary (Switch between AI and Google based on type)
    let aiResult;
    if (type === 'guided') {
        aiResult = await itineraryService.generateGoogleDate(params);
    } else {
        aiResult = await itineraryService.generateAIDate(params);
    }

    // 3. Draft Mode: return the constructed plan without database persistence
    if (params.draft) {
        let steps = [];
        let title = 'Your Date Plan';
        let description = 'A curated experience by Spark AI';

        if (Array.isArray(aiResult.data)) {
            steps = aiResult.data;
        } else if (typeof aiResult.data === 'object' && aiResult.data !== null) {
            steps = aiResult.data.steps || 
                    aiResult.data.itinerary || 
                    aiResult.data.schedule || 
                    aiResult.data.plan || 
                    aiResult.data.date || 
                    aiResult.data.timeline || 
                    [];
            title = aiResult.data.title || title;
            description = aiResult.data.description || description;
        } else if (typeof aiResult.data === 'string' && aiResult.data.trim().length > 0) {
            steps = [{
                time: "Today",
                activity: "Date Experience",
                venue: "See Details Below",
                location: params.location || "Nearby",
                description: aiResult.data,
                vibe: params.vibe || 'classic'
            }];
            description = "Raw plan generated by Spark AI";
        }

        return {
            id: 'draft_' + Math.random().toString(36).substr(2, 9),
            user_id: userId,
            location: params.location || params.city || 'NYC',
            vibe: params.vibe || 'chill',
            budget: params.budget || 'smart',
            itinerary: {
                steps: steps, // Already enriched by Google Places
                metadata: {
                    user_input: params.prompt || params.preferences || params.interests || '',
                    location: params.location || params.city,
                    vibe: params.vibe,
                    budget: params.budget,
                    planDate: params.planDate || new Date().toISOString().split('T')[0]
                }
            },
            title: title,
            description: description,
            lat: params.lat,
            lng: params.lng,
            is_favorite: false,
            generation_type: aiResult.source === 'GOOGLE_PLACES' ? 'guided' : 'classic',
            is_draft: true
        };
    }

    // 4. Persist to Database
    const savedPlan = await itineraryService.savePlan(supabase, userId, params, aiResult);

    return savedPlan;
};

export const saveDraftPlan = async (supabase, userId, planData) => {
    const { data, error } = await supabase
        .from('plans')
        .insert([{
            user_id: userId,
            location: planData.location || 'NYC',
            vibe: planData.vibe || 'chill',
            budget: planData.budget || 'smart',
            itinerary: planData.itinerary,
            title: planData.title || 'Your Date Plan',
            description: planData.description || 'A curated experience by Spark AI',
            lat: planData.lat,
            lng: planData.lng,
            is_favorite: false,
            generation_type: planData.generation_type || 'classic',
            created_at: new Date().toISOString()
        }])
        .select()
        .single();

    if (error) throw error;
    return data;
};

export const recreatePlanFlow = async (supabase, userId, planId, typeOverride = null) => {
    // 1. Get original plan to determine type if not provided
    const { data: original, error: fetchError } = await supabase
        .from('plans')
        .select('generation_type')
        .eq('id', planId)
        .single();
    
    if (fetchError || !original) {
        throw new Error('Original plan not found');
    }

    const type = typeOverride || original.generation_type || 'classic';

    // 2. Check Usage Limits
    const usage = await userService.checkUsageLimits(supabase, userId, type);
    if (!usage.allowed) {
        throw { status: 403, message: 'Limit reached', code: 'LIMIT_REACHED' };
    }

    // 3. Recreate Plan (ItineraryService handles the lookup and re-generation)
    const newPlan = await itineraryService.recreatePlan(supabase, planId);

    return newPlan;
};
