services:
  - type: web
    name: datespark
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVarGroups: []
    autoDeploy: true
